import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ReduxProvider from "@/redux/provider";
import AuthModal from "@/components/auth/authModel";
import RecaptchaProvider from "@/providers/RecaptchaProvider";
import { ToastContainer } from "react-toastify";
import { Suspense } from "react";
import AuthSessionProvider from "@/providers/SessionProvider";
import LoginPrompt from "@/components/auth/LoginPrompt";

import GLobalDialogs from "@/shared/GlobalDialogs";
import CartInitializer from "@/providers/CartInitializer";
import WishlistInitializer from "@/providers/WishlistInitializer";
import LocationInitializer from "@/providers/LocationInitializer";
import LocationSelection from "@/components/location-selection/LocationSelection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Alkhafeef Next Js",
  description: "Generated by create next app",
  icons: {
    icon: "/images/alkhafeef_logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <RecaptchaProvider>
          <AuthSessionProvider>
            <ReduxProvider>
              <Suspense fallback={null}>
                <LoginPrompt />
              </Suspense>
              <ToastContainer />
              <GLobalDialogs />
              <CartInitializer/>
              <WishlistInitializer/>
              <LocationInitializer />
              <Header />
              <main className="bg-[#f6efe5]">{children}</main>

              <Footer />
              <AuthModal />
              <LocationSelection />
            </ReduxProvider>
          </AuthSessionProvider>
        </RecaptchaProvider>
      </body>
    </html>
  );
}
