import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ReduxProvider from "@/redux/provider";
import AuthModal from "@/components/auth/authModel";
import RecaptchaProvider from "@/providers/RecaptchaProvider";
import { ToastContainer } from "react-toastify";

import AuthInitializer from "@/providers/AuthInitializer";
import GLobalDialogs from "@/shared/GlobalDialogs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>
        <RecaptchaProvider>
          <ToastContainer />

          <ReduxProvider>
            <AuthInitializer />
            <GLobalDialogs />
            <Header />

            <main className="bg-[#f6efe5]">{children}</main>

            <Footer />

            <AuthModal />
          </ReduxProvider>
        </RecaptchaProvider>
      </body>
    </html>
  );
}
